server:
  port: 9010

spring:
  # Database Connection
  datasource:
    url: jdbc:mariadb://localhost:3306/cmms?useUnicode=true&characterEncoding=utf8
    username: root
    password: # Use a secure way to provide this, e.g., environment variables
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: validate # Use Flyway for schema management, so validate the schema
    show-sql: true # Good for development
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  # Flyway
  flyway:
    enabled: true
    baseline-on-migrate: true # Creates a baseline if no metadata table exists
    locations: classpath:db/migration # Location of migration scripts
    schemas: cmms # The schema Flyway will manage

  # Thymeleaf
  thymeleaf:
    cache: false # Disable caching for development

  # Enable HiddenHttpMethodFilter
  mvc:
    hiddenmethod:
      filter:
        enabled: true

# Logging
logging:
  level:
    root: INFO
    com.platform.cmms10: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE # To see bind parameters
